// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcCAnbLqPcWNz-HQPsNCMnki71IpSK0mg',
    appId: '1:1059012335519:web:e6c8e515557b4a4de5cfaa',
    messagingSenderId: '1059012335519',
    projectId: 'agenda-af1fb',
    authDomain: 'agenda-af1fb.firebaseapp.com',
    storageBucket: 'agenda-af1fb.appspot.com',
    measurementId: 'G-1TWXY16QS5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByv4RU77NTnyxXX2wzyHXd2TUkv0xAD30',
    appId: '1:1059012335519:android:4f415f93a3d8f4dce5cfaa',
    messagingSenderId: '1059012335519',
    projectId: 'agenda-af1fb',
    storageBucket: 'agenda-af1fb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCh8hABI8YxlGGnG_NGUc09B6_ZXmNsnYc',
    appId: '1:1059012335519:ios:cf9bd817434b6a25e5cfaa',
    messagingSenderId: '1059012335519',
    projectId: 'agenda-af1fb',
    storageBucket: 'agenda-af1fb.appspot.com',
    iosClientId: '1059012335519-uusa198ekd499fg2qicmo3ibpv2vpikj.apps.googleusercontent.com',
    iosBundleId: 'com.example.agenda',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCh8hABI8YxlGGnG_NGUc09B6_ZXmNsnYc',
    appId: '1:1059012335519:ios:cf9bd817434b6a25e5cfaa',
    messagingSenderId: '1059012335519',
    projectId: 'agenda-af1fb',
    storageBucket: 'agenda-af1fb.appspot.com',
    iosClientId: '1059012335519-uusa198ekd499fg2qicmo3ibpv2vpikj.apps.googleusercontent.com',
    iosBundleId: 'com.example.agenda',
  );
}
